version: '3.6'

services:
  nginx:
    image: nginx:latest         #name of the image
    container_name: nginx       #name of the container you want to build
    restart: always             #allow the connection to restart if it gets disconnected
    ports:
      - 80:80   #specify the unencrypt port
      - 443:443 #specify the encrypt port but will need ssl later
    volumes:
      - /home/docker/nginx/nginx.conf:/etc/nginx/nginx.conf #connect the host configuration files to docker config files
      - /home/docker/nginx/conf.d:/etc/nginx/templates #connect the host configuration files to docker config files
    command: [nginx-debug, '-g', 'daemon off;']

  simple-app:
    image: montibot/simple-app:0.0.1  #name of the docker image
    container_name: simple-app #name of the container
    restart: always.         #allow the connection to restart if it gets disconnected
    ports:
      - 9898:3838                   #port where the application is published on   
    volumes:
      - /home/rchau88/simple-app/shinyApps/:/srv/shiny-server/           #location to the codebse or data files
      - /home/xposome/simple-app/shinyApps-log/:/var/log/shiny-server/   #location to store log information from the shiny app
